FROM python:3.13

# Instaluj ffmpeg dla pydub
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

# Ustaw katalog roboczy w kontenerze
WORKDIR /app

# Skopiuj zależności
COPY requirements.txt .

# Instaluj zależności
RUN pip install --no-cache-dir -r requirements.txt

# Skopiuj resztę plików projektu
COPY . .

# Utwórz folder audio_files i nadaj uprawnienia do zapisu
RUN mkdir -p /app/audio_files && chmod 777 /app/audio_files

# Uruchom aplikację
CMD ["python", "run.py"]
