services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:8080"
    restart: on-failure:10
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      # Database connection info are read from .env (see .env.example)
    depends_on:
      - db

    volumes:
      - ./:/app
      - ./audio_files:/app/audio_files

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-hackyeah}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin1}
      LANG: pl_PL.UTF-8
      LC_ALL: pl_PL.UTF-8
      POSTGRES_INITDB_ARGS: "--locale=pl_PL.UTF-8 --encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "5050:8080"
    depends_on:
      - db

volumes:
  postgres_data:
